Repository Berakah-Tech/lyric-app, pull requests merged in 2022-11, with the labels that each got.

#7 ⚡ IMPROVE: refactor validation schema
  src/server/trpc/router/song.ts
  src/types/types.d.ts
  src/validations/songValidations.ts
Labels: back-end

#9 ⏫ UPDATE: Schema
  prisma/schema.prisma
Labels: back-end

#11 Dummy-Data
  prisma/schema.prisma
  src/pages/index.tsx
  src/server/trpc/router/_app.ts
  src/server/trpc/router/example.ts
  src/server/trpc/router/song.ts
  src/types/types.d.ts
  src/validations/songValidations.ts
Labels: back-end

#16 ⚡ IMPROVE: added data to book page
  src/pages/admin/book/index.tsx
  src/server/trpc/router/_app.ts
  src/server/trpc/router/book.router.ts
Labels: front-end

#17 Admin-user-page
  src/components/AdminHeader.tsx
  src/components/AdminSidebar.tsx
  src/layouts/AdminLayout.tsx
  src/pages/admin/user/index.tsx
  src/server/trpc/router/_app.ts
  src/server/trpc/router/user.router.ts
Labels: front-end, back-end

#18 Adminaide-pages
  src/pages/admin/category/index.tsx
  src/pages/admin/song/index.tsx
  src/pages/admin/user/index.tsx
  src/server/trpc/router/_app.ts
  src/server/trpc/router/category.router.ts
  src/server/trpc/router/song.router.ts
Labels: front-end, back-end

#19 ⏫ UPDATE: song schema
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  prisma/schema.prisma
  src/layouts/AdminLayout.tsx
  src/pages/admin/song/index.tsx
  src/styles/globals.css
  src/types/types.d.ts
  src/validations/zodSchemas.ts
Labels: back-end
